use_frameworks!

platform :ios, '9.0'

target 'MKBaseBleModule_Example' do
  pod 'MKBaseBleModule', :path => '../'

  target 'MKBaseBleModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
